rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include

urlpatterns = [
    path('not-admin/', admin.site.urls),
    path('', include('rentapp.urls')),
    path('accounts/', include('accounts.urls')),
    url(r'^accounts/login/$', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

rentapp/urls.py
from accounts.views import user_login
from django.urls import path, re_path
from rentapp.views import home
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'rentpayment'

urlpatterns = [
    path('',user_login, name='login'),
    re_path(r'^home/$', home, name='home'),
    path('employee/property_list', views.property_list, name='property_list'),
    path('employee/add_property', views.add_property, name='add_property'),
    path('employee/<int:pk>/edit/', views.property_edit, name='property_edit'),
    path('employee/<int:pk>/delete/', views.property_delete, name='property_delete'),
    path('employee/maintenance_request_list', views.maintenance_request_list, name='maintenance_request_list'),
    path('employee/<int:pk>/maintenance_request_update', views.maintenance_request_update, name='maintenance_request_update'),
    path('tenant/pay_rent', views.pay_rent, name='pay_rent'),
    path('tenant/payment_detail', views.payment_detail, name='payment_detail'),
    path('tenant/payment_success', views.payment_success, name='payment_success'),
    path('tenant/payment_history', views.payment_history, name='payment_history'),
    path('tenant/maintenance_request', views.maintenance_request, name='maintenance_request'),
    path('tenant/maintenance_request_history', views.maintenance_request_history, name='maintenance_request_history'),
    url(r'^properties_json/', views.PropertyList.as_view()),
    url(r'^maintenancerequest_json/', views.MaintenanceRequestList.as_view()),
    url(r'^payment_json/', views.PaymentList.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

rentapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

# Create your models here.
from rent import settings


class Property(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    apt_no = models.CharField(max_length=10)
    property_name = models.CharField(max_length=50)
    rent_amount = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)

    def __str__(self):
        return str(self.apt_no)

class Payment(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    amount_paid = models.DecimalField(max_digits=9, decimal_places=2)
    paid_date = models.DateField()

    def __str__(self):
        return str(self.amount_paid)


class MaintenanceRequest(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    priority = models.CharField(max_length=50)
    problem = models.TextField()
    status = models.CharField(max_length=50, default="New")
    resolved_by = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.problem)

rentapp/forms.py
from django import forms
from .models import Payment, Property, MaintenanceRequest


class PropertyForm(forms.ModelForm):
   class Meta:
       model = Property
       fields = ('user', 'apt_no', 'property_name', 'rent_amount', 'address', 'city', 'state', 'zipcode')

class PaymentForm(forms.ModelForm):
   class Meta:
       model = Payment
       fields = ('amount_paid', 'paid_date')

class MaintenanceRequestForm(forms.ModelForm):
   class Meta:
       model = MaintenanceRequest
       fields = ('property', 'priority', 'status', 'problem', 'resolved_by')

rentapp/views.py
# Create your views here.
from accounts.models import Profile, CustomUser
from django.contrib.auth.decorators import login_required
from django import forms
from django.utils import timezone
from rent import settings
from rentapp.decorators import employee_required, tenant_required
from rentapp.forms import PropertyForm, MaintenanceRequestForm, PaymentForm
from rentapp.models import Property, Payment, MaintenanceRequest
from django.shortcuts import render, redirect, get_object_or_404
from rentapp.serializers import PropertySerializer, MaintenanceRequestSerializer, PaymentSerializer
from rest_framework.views import APIView
from rest_framework.response import Response

@login_required
def home(request):
    return render(request, 'rentapp/home.html')

@login_required
@employee_required
def property_list(request):
    property = Property.objects.filter()
    return render(request, 'rentapp/employee/property_list.html',
                  {'property': property})

@login_required
@employee_required
def add_property(request):
    if request.method == "POST":
        form = PropertyForm(request.POST)
        if form.is_valid():
            property = form.save(commit=False)
            property.created_date = timezone.now()
            property.save()
            property = Property.objects.filter()
            return render(request, 'rentapp/employee/property_list.html',
                          {'property': property})
    else:
        form = PropertyForm()
        userids = Profile.objects.filter(is_tenant=True).values("user_id")
        form.fields["user"].queryset = CustomUser.objects.filter(id__in=userids)
    # print("Else")
    return render(request, 'rentapp/employee/add_property.html', {'form': form})

@login_required
@employee_required
def property_edit(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == "POST":
        # update
        form = PropertyForm(request.POST, instance=property)
        if form.is_valid():
            property = form.save(commit=False)
            property.updated_date = timezone.now()
            property.save()
            property = Property.objects.filter()
            return render(request, 'rentapp/employee/property_list.html',
                          {'property': property})
    else:
        # edit
        form = PropertyForm(instance=property)
    return render(request, 'rentapp/employee/property_edit.html', {'form': form})

@login_required
@employee_required
def property_delete(request, pk):
    property = get_object_or_404(Property, pk=pk)
    property.delete()
    return redirect('rentpayment:property_list')

@login_required
@tenant_required
def pay_rent(request):
    property = Property.objects.filter(user=request.user).first()
    is_rent_paid = _is_rent_paid(request)
    return render(request, 'rentapp/tenant/pay_rent.html', {'property': property, 'currentuser':request.user, 'is_rent_paid':is_rent_paid})

def _is_rent_paid(request):
    payment = Payment.objects.filter(user=request.user, paid_date__month=timezone.now().month)
    if len(payment) == 0:
        return False
    else:
        return True

@login_required
@tenant_required
def payment_detail(request):
    property = Property.objects.filter(user=request.user).first()
    is_rent_paid = _is_rent_paid(request)
    return render(request, 'rentapp/tenant/payment_detail.html', {'property': property, 'currentuser':request.user, 'is_rent_paid':is_rent_paid})

@login_required
@tenant_required
def payment_success(request):
    if request.method == "POST":
        form = PaymentForm(request.POST)
        payment = Payment.objects.create(user=request.user, paid_date=timezone.now(),amount_paid=request.POST.get('rentamount'), property= Property.objects.filter(user=request.user).first())
        payment.save()
        return render(request, 'rentapp/tenant/payment_success.html')
    else:
        form = PaymentForm()
        # print("Else")
    return render(request, 'rentapp/tenant/payment_detail.html', {'currentuser':request.user})

@login_required
@tenant_required
def payment_history(request):
    payment = Payment.objects.filter(user=request.user)
    print(payment)
    return render(request, 'rentapp/tenant/payment_history.html', {'payment':payment})

@login_required
@tenant_required
def maintenance_request(request):
    if request.method == "POST":
        form = MaintenanceRequestForm(request.POST)
        if form.is_valid():
            print(request.POST)
            maintenancerequest = form.save(commit=False)
            maintenancerequest.created_date = timezone.now()
            maintenancerequest.user = request.user
            maintenancerequest.save()
            maintenancerequest = MaintenanceRequest.objects.filter()
            return render(request, 'rentapp/tenant/maintenance_request_history.html', {'maintenancerequest':maintenancerequest, 'currentuser':request.user})
    else:
        form = MaintenanceRequestForm()
        form.fields["property"].queryset = Property.objects.filter(user_id=request.user)
        form.fields["status"].widget.attrs['readonly'] = True
        form.fields["resolved_by"].widget= forms.HiddenInput()
        # print("Else")
    return render(request, 'rentapp/tenant/maintenance_request.html', {'form': form, 'currentuser':request.user})

@login_required
@tenant_required
def maintenance_request_history(request):
    maintenancerequest = MaintenanceRequest.objects.filter()
    return render(request, 'rentapp/tenant/maintenance_request_history.html', {'maintenancerequest': maintenancerequest, 'currentuser':request.user})

@login_required
@employee_required
def maintenance_request_list(request):
    maintenancerequest = MaintenanceRequest.objects.filter()
    return render(request, 'rentapp/employee/maintenance_request_list.html', {'maintenancerequest': maintenancerequest})

@login_required
@employee_required
def maintenance_request_update(request, pk):
    maintenancerequest = get_object_or_404(MaintenanceRequest, pk=pk)
    if request.method == "POST":
        # update
        form = MaintenanceRequestForm(request.POST, instance=maintenancerequest)
        if form.is_valid():
            maintenancerequest = form.save(commit=False)
            maintenancerequest.updated_date = timezone.now()
            maintenancerequest.save()
            maintenancerequest = MaintenanceRequest.objects.filter()
            return render(request, 'rentapp/employee/maintenance_request_list.html',
                          {'maintenancerequest': maintenancerequest})
    else:
        # edit
        maintenancerequest.resolved_by = request.user
        form = MaintenanceRequestForm(instance=maintenancerequest)

    return render(request, 'rentapp/employee/maintenance_request_update.html', {'form': form})


#API
class PropertyList(APIView):
    def get(self,request):
        properties_json = Property.objects.all()
        serializer = PropertySerializer(properties_json, many=True)
        return Response(serializer.data)

class MaintenanceRequestList(APIView):
    def get(self,request):
        maintenancerequest_json = MaintenanceRequest.objects.all()
        serializer = MaintenanceRequestSerializer(maintenancerequest_json, many=True)
        return Response(serializer.data)

class PaymentList(APIView):
    def get(self,request):
        payment_json = Payment.objects.all()
        serializer = PaymentSerializer(payment_json, many=True)
        return Response(serializer.data)

rentapp/templates/base.html
{% load staticfiles %}

<html lang="en">
<head>
    <title>Park Place Rent Payment</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/custom.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body id="app-layout" >
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/home">
                Park Place
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            {% if user.is_authenticated %}
                {% if user.profile.is_employee %}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'rentpayment:add_property' %}">Add Property</a></li>
                       <li><a href="{% url 'rentpayment:property_list' %}">Property List</a></li>
                        <li><a href="{% url 'rentpayment:maintenance_request_list' %}">Maintenance Request List</a></li>
                    </ul>
                {%endif %}
            {% endif %}
            {% if user.is_authenticated %}
                {% if user.profile.is_tenant%}
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'rentpayment:pay_rent' %}">Pay Rent</a></li>
                        <li><a href="{% url 'rentpayment:payment_history' %}">Payment History</a></li>
                       <li><a href="{% url 'rentpayment:maintenance_request_history' %}">Maintenance Request</a></li>
                    </ul>
                {% endif %}
            {% endif %}
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                {% else %}
                    <li class="nav-item dropdown">
                            <a id="pages" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                               class="nav-link dropdown-toggle"><i class="fa fa-signing"></i>Register
                            </a>
                            <div aria-labelledby="pages" class="dropdown-menu">
                                <a href="{% url 'employee_register' %}" class="dropdown-item">Employee</a>
                                <a href="{% url 'tenant_register' %}" class="dropdown-item">Tenant</a>
                            </div>
                    </li>
                    <a href="{% url 'login' %}" class="btn navbar-btn btn-outline-light mb-5 mb-lg-0">
                        <i class="fa fa-sign-in"></i>Login
                    </a>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-6">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>