rent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include

urlpatterns = [
    path('not-admin/', admin.site.urls),
    path('', include('rentapp.urls')),
    path('accounts/', include('accounts.urls')),
    url(r'^accounts/login/$', LoginView.as_view(template_name='accounts/login.html'), name="login"),
    url(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

rentapp/urls.py
from accounts.views import user_login
from django.urls import path, re_path
from rentapp.views import home
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'rentpayment'

urlpatterns = [
    path('',user_login, name='login'),
    re_path(r'^home/$', home, name='home'),
    path('employee/property_list', views.property_list, name='property_list'),
    path('employee/add_property', views.add_property, name='add_property'),
    path('employee/<int:pk>/edit/', views.property_edit, name='property_edit'),
    path('employee/<int:pk>/delete/', views.property_delete, name='property_delete'),
    path('employee/maintenance_request_list', views.maintenance_request_list, name='maintenance_request_list'),
    path('employee/<int:pk>/maintenance_request_update', views.maintenance_request_update, name='maintenance_request_update'),
    path('tenant/pay_rent', views.pay_rent, name='pay_rent'),
    path('tenant/payment_detail', views.payment_detail, name='payment_detail'),
    path('tenant/payment_success', views.payment_success, name='payment_success'),
    path('tenant/payment_history', views.payment_history, name='payment_history'),
    path('tenant/maintenance_request', views.maintenance_request, name='maintenance_request'),
    path('tenant/maintenance_request_history', views.maintenance_request_history, name='maintenance_request_history'),
    url(r'^properties_json/', views.PropertyList.as_view()),
    url(r'^maintenancerequest_json/', views.MaintenanceRequestList.as_view()),
    url(r'^payment_json/', views.PaymentList.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

rentapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone

# Create your models here.
from rent import settings


class Property(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    apt_no = models.CharField(max_length=10)
    property_name = models.CharField(max_length=50)
    rent_amount = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)

    def __str__(self):
        return str(self.apt_no)

class Payment(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    amount_paid = models.DecimalField(max_digits=9, decimal_places=2)
    paid_date = models.DateField()

    def __str__(self):
        return str(self.amount_paid)


class MaintenanceRequest(models.Model):
    user = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    priority = models.CharField(max_length=50)
    problem = models.TextField()
    status = models.CharField(max_length=50, default="New")
    resolved_by = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return str(self.problem)

rentapp/forms.py
from django import forms
from .models import Payment, Property, MaintenanceRequest


class PropertyForm(forms.ModelForm):
   class Meta:
       model = Property
       fields = ('user', 'apt_no', 'property_name', 'rent_amount', 'address', 'city', 'state', 'zipcode')

class PaymentForm(forms.ModelForm):
   class Meta:
       model = Payment
       fields = ('amount_paid', 'paid_date')

class MaintenanceRequestForm(forms.ModelForm):
   class Meta:
       model = MaintenanceRequest
       fields = ('property', 'priority', 'status', 'problem', 'resolved_by')

rentapp/views.py
# Create your views here.
from accounts.models import Profile, CustomUser
from django.contrib.auth.decorators import login_required
from django import forms
from django.utils import timezone
from rent import settings
from rentapp.decorators import employee_required, tenant_required
from rentapp.forms import PropertyForm, MaintenanceRequestForm, PaymentForm
from rentapp.models import Property, Payment, MaintenanceRequest
from django.shortcuts import render, redirect, get_object_or_404
from rentapp.serializers import PropertySerializer, MaintenanceRequestSerializer, PaymentSerializer
from rest_framework.views import APIView
from rest_framework.response import Response

@login_required
def home(request):
    return render(request, 'rentapp/home.html')

@login_required
@employee_required
def property_list(request):
    property = Property.objects.filter()
    return render(request, 'rentapp/employee/property_list.html',
                  {'property': property})

@login_required
@employee_required
def add_property(request):
    if request.method == "POST":
        form = PropertyForm(request.POST)
        if form.is_valid():
            property = form.save(commit=False)
            property.created_date = timezone.now()
            property.save()
            property = Property.objects.filter()
            return render(request, 'rentapp/employee/property_list.html',
                          {'property': property})
    else:
        form = PropertyForm()
        userids = Profile.objects.filter(is_tenant=True).values("user_id")
        form.fields["user"].queryset = CustomUser.objects.filter(id__in=userids)
    # print("Else")
    return render(request, 'rentapp/employee/add_property.html', {'form': form})

@login_required
@employee_required
def property_edit(request, pk):
    property = get_object_or_404(Property, pk=pk)
    if request.method == "POST":
        # update
        form = PropertyForm(request.POST, instance=property)
        if form.is_valid():
            property = form.save(commit=False)
            property.updated_date = timezone.now()
            property.save()
            property = Property.objects.filter()
            return render(request, 'rentapp/employee/property_list.html',
                          {'property': property})
    else:
        # edit
        form = PropertyForm(instance=property)
    return render(request, 'rentapp/employee/property_edit.html', {'form': form})

@login_required
@employee_required
def property_delete(request, pk):
    property = get_object_or_404(Property, pk=pk)
    property.delete()
    return redirect('rentpayment:property_list')

@login_required
@tenant_required
def pay_rent(request):
    property = Property.objects.filter(user=request.user).first()
    is_rent_paid = _is_rent_paid(request)
    return render(request, 'rentapp/tenant/pay_rent.html', {'property': property, 'currentuser':request.user, 'is_rent_paid':is_rent_paid})

def _is_rent_paid(request):
    payment = Payment.objects.filter(user=request.user, paid_date__month=timezone.now().month)
    if len(payment) == 0:
        return False
    else:
        return True

@login_required
@tenant_required
def payment_detail(request):
    property = Property.objects.filter(user=request.user).first()
    is_rent_paid = _is_rent_paid(request)
    return render(request, 'rentapp/tenant/payment_detail.html', {'property': property, 'currentuser':request.user, 'is_rent_paid':is_rent_paid})

@login_required
@tenant_required
def payment_success(request):
    if request.method == "POST":
        form = PaymentForm(request.POST)
        payment = Payment.objects.create(user=request.user, paid_date=timezone.now(),amount_paid=request.POST.get('rentamount'), property= Property.objects.filter(user=request.user).first())
        payment.save()
        return render(request, 'rentapp/tenant/payment_success.html')
    else:
        form = PaymentForm()
        # print("Else")
    return render(request, 'rentapp/tenant/payment_detail.html', {'currentuser':request.user})

@login_required
@tenant_required
def payment_history(request):
    payment = Payment.objects.filter(user=request.user)
    print(payment)
    return render(request, 'rentapp/tenant/payment_history.html', {'payment':payment})

@login_required
@tenant_required
def maintenance_request(request):
    if request.method == "POST":
        form = MaintenanceRequestForm(request.POST)
        if form.is_valid():
            print(request.POST)
            maintenancerequest = form.save(commit=False)
            maintenancerequest.created_date = timezone.now()
            maintenancerequest.user = request.user
            maintenancerequest.save()
            maintenancerequest = MaintenanceRequest.objects.filter()
            return render(request, 'rentapp/tenant/maintenance_request_history.html', {'maintenancerequest':maintenancerequest, 'currentuser':request.user})
    else:
        form = MaintenanceRequestForm()
        form.fields["property"].queryset = Property.objects.filter(user_id=request.user)
        form.fields["status"].widget.attrs['readonly'] = True
        form.fields["resolved_by"].widget= forms.HiddenInput()
        # print("Else")
    return render(request, 'rentapp/tenant/maintenance_request.html', {'form': form, 'currentuser':request.user})

@login_required
@tenant_required
def maintenance_request_history(request):
    maintenancerequest = MaintenanceRequest.objects.filter()
    return render(request, 'rentapp/tenant/maintenance_request_history.html', {'maintenancerequest': maintenancerequest, 'currentuser':request.user})

@login_required
@employee_required
def maintenance_request_list(request):
    maintenancerequest = MaintenanceRequest.objects.filter()
    return render(request, 'rentapp/employee/maintenance_request_list.html', {'maintenancerequest': maintenancerequest})

@login_required
@employee_required
def maintenance_request_update(request, pk):
    maintenancerequest = get_object_or_404(MaintenanceRequest, pk=pk)
    if request.method == "POST":
        # update
        form = MaintenanceRequestForm(request.POST, instance=maintenancerequest)
        if form.is_valid():
            maintenancerequest = form.save(commit=False)
            maintenancerequest.updated_date = timezone.now()
            maintenancerequest.save()
            maintenancerequest = MaintenanceRequest.objects.filter()
            return render(request, 'rentapp/employee/maintenance_request_list.html',
                          {'maintenancerequest': maintenancerequest})
    else:
        # edit
        maintenancerequest.resolved_by = request.user
        form = MaintenanceRequestForm(instance=maintenancerequest)

    return render(request, 'rentapp/employee/maintenance_request_update.html', {'form': form})


#API
class PropertyList(APIView):
    def get(self,request):
        properties_json = Property.objects.all()
        serializer = PropertySerializer(properties_json, many=True)
        return Response(serializer.data)

class MaintenanceRequestList(APIView):
    def get(self,request):
        maintenancerequest_json = MaintenanceRequest.objects.all()
        serializer = MaintenanceRequestSerializer(maintenancerequest_json, many=True)
        return Response(serializer.data)

class PaymentList(APIView):
    def get(self,request):
        payment_json = Payment.objects.all()
        serializer = PaymentSerializer(payment_json, many=True)
        return Response(serializer.data)

rentapp/templates/rentapp/employee/add_property.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add Property</h1>
    <form method="POST" class="property-form">{% csrf_token %}
          {{ form|crispy }}
        <br>
        <button type="submit" class="save btn btn-default">Add</button>
    </form>
{% endblock %}

rentapp/templates/rentapp/employee/maintenance_request_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 {% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <div class="row">
        <h2 style="padding-left: 15Px">Maintenance Request List</h2>
    </div>
<div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>User</th>
                <th>Apt No</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Problem</th>
                <th>Resolved By</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for maintenancerequest in maintenancerequest %}
                <tr>
                    <td>{{ maintenancerequest.user }}</td>
                    <td>{{ maintenancerequest.property }}</td>
                    <td>{{ maintenancerequest.priority }}</td>
                    <td>{{ maintenancerequest.status}}</td>
                    <td>{{ maintenancerequest.problem}}</td>
                    <td>{{ maintenancerequest.resolved_by}}</td>
                    <td><a href="{% url 'rentpayment:maintenance_request_update' pk=maintenancerequest.pk %}" class="btn btn-warning">Update</a>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </div>
    </body>
    </html>
{% endblock %}

rentapp/templates/rentapp/employee/maintenance_request_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Update Maintenance Request</h1>
    <form method="POST" class="maintenancerequest-form">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

rentapp/templates/rentapp/employee/property_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
    <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
    </form>

{% endblock %}

rentapp/templates/rentapp/employee/property_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Property</h1>
    <form method="POST" class="property-form">{% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

rentapp/templates/rentapp/employee/property_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
 {% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <div class="row">
        <h2 style="padding-left: 15Px">Property List</h2>
    </div>
<div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Tenant</th>
                <th>Apt No</th>
                <th>Property Name</th>
                <th>Rent</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for property in property %}
                <tr>
                    <td>{{ property.user }}</td>
                    <td>{{ property.apt_no }}</td>
                    <td>{{ property.property_name }}</td>
                    <td>{{ property.rent_amount }}</td>
                    <td>{{ property.address }}</td>
                    <td>{{ property.city }}</td>
                    <td>{{ property.state }}</td>
                    <td>{{ property.zipcode }}</td>
                    <td><a href="{% url 'rentpayment:property_edit' pk=property.pk %}" class="btn btn-warning">Edit</a>

                    <td><a href="{% url 'rentpayment:property_delete' pk=property.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </div>
    </body>
    </html>
{% endblock %}